### ISSUE TITLE
Docker Compose V1 syntax is completely deprecated

### ISSUE THREAD

**Issue by PeKaMe** [ei23com/diy-smart-home#6]
Running Ubuntu server 22.04.4 LTS.

Today I did an apt update and apt upgrade which ran through a few updates, and then I pulled new docker images via docker-compose pull. After I tried to restart the containers via docker-compose, I got a bunch of errors regarding container config and many of the containers refused to start. Then when I run docker ps -a, I see a bunch of the container names have changed to include a random string of characters before the prior name (e.g. swag is now 5f6bfe94c235_swag). I didn't change anything in the docker-compose.yml file and it had been working fine before this.

When I run sudo docker-compose up -d, I get the following output:

```ei23@odroid:~$ bash ei23.sh dc
grafana is up-to-date
paperless_broker is up-to-date
nextcloud_db is up-to-date
Recreating d6da303d63b4_portainer ...
traefik is up-to-date
Recreating 9f1a5aeceed5_ncredis   ...
paperless_db is up-to-date
homeassistant is up-to-date
vscode is up-to-date
mqtt-explorer is up-to-date
influxdb2 is up-to-date
tasmoadmin is up-to-date
mosquitto is up-to-date
paperless_web is up-to-date

ERROR: for d6da303d63b4_portainer  'ContainerConfig'

ERROR: for 9f1a5aeceed5_ncredis  'ContainerConfig'

ERROR: for portainer  'ContainerConfig'

ERROR: for nextcloud_broker  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
KeyError: 'ContainerConfig'
```
I'm able to manually start the containers by using the command
i found the solution in this post
[https://askubuntu.com/questions/1396689/docker-compose-cant-execute-command-docker-compose-not-found](url)

Docker Compose V1 has the command syntax docker-compose (docker-compose is a separate command).
Docker Compose V2 has the command syntax docker compose (compose is a subcommand of the docker command).

Since we have installed Docker Compose V2 branch, you can't use docker-compose up -d, but should instead use the correct V2 syntax:

`docker compose up -d`

In the script ei23.sh, I replaced all instances of "docker-compose" with "docker compose". After that, the following command was executed again:

`bash ei23.sh dc`

The script ei23.sh was executed without errors, enclosed the output:

```
Container grafana           Started
Container influxdb2         Started
Container mqtt-explorer     Started
Container tasmoadmin        Started
Container mosquitto         Started
Container portainer         Started
Container homeassistant     Started
Container nextcloud_db      Started
Container traefik           Started
Container vscode            Started
Container nextcloud_broker  Started
Container paperless_db      Started
Container paperless_broker  Started
Container paperless_web     Started
Container nextcloud         Started
```

**Comment by ei23fxg** [comment]
Did you run "ei23 update" or "ei23 ei23update" recently?
The script has migrated to docker compose v2 last week:
[History Log](https://github.com/ei23com/diy-smart-home/commit/b711077cca9056f9dbac317009c8c4092d6f50eb#diff-05638c48078ca05e7450ad52a6dff24699b563504154937af26913c647f5441c)
Also still has backwards compatibility with v1

If you run Script < v1.1 also look for breaking changes:
[Breaking Changes](https://diy-smart-home.ei23.com/start/update/)
